### ISSUE TITLE
Try Absolute rather than Relative

### ISSUE THREAD

**Issue by tjhickey724** [tjhickey724/MuseBandBiofeedback#11]
Look at a couple of subjects, one with excellent prediction and one with poor prediction.
Try to use Absolute bands instead of Relative with the 4-fold crossover validation
and see if we get better, worse, or the same results ...

**Comment by xqu** [comment]
tried absolute value, seems provide better prediction accuracy,  screen shots in Google drive,
Folder 'Absolute_or_Relative' ,  code updated here on github. ProcessCSV.java and Process1.java
